apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-run
  namespace: llm-d-benchmark
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: llm-d-benchmark
    spec:
      serviceAccountName: benchmark-runner
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: evaluation
        # TODO: UPDATE IMAGE
        image: llm-d-benchmark:quickstart
        imagePullPolicy: Never
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        command: ["sh"]
        args: ["-c", "cat /workspace/config/llmdbench_workload.yaml && mkdir /workspace/profiles/ && mkdir /workspace/profiles/fmperf/ && ln -sf /workspace/config/llmdbench_workload.yaml /workspace/profiles/fmperf/llmdbench_workload.yaml && python3 /workspace/workload/harnesses/fmperf-llm-d-benchmark.py"]
        envFrom:
        - configMapRef:
            name: benchmark-env
        volumeMounts:
        - name: results
          mountPath: /requests
        - name: workload-file
          mountPath: /workspace/config
          readOnly: true
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: benchmark-results-pvc
      - name: workload-file
        configMap:
          name: benchmark-workload-config
      restartPolicy: Never
